<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/4/21
 * Time: 10:59
 */

namespace app\modules\api\controllers;


class BaseController extends  \app\controllers\BaseController
{

    public $enableCsrfValidation=false;

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}